namespace IChingLibrary.Generators;

[Generator]
public sealed class IChingElementGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "IChingLibrary.Core.Annotations.IChingElementEnumAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => TryCreateModel(ctx))
            .Where(static model => model is not null)
            .Select(static (model, _) => model!.Value);

        context.RegisterSourceOutput(models, static (spc, model) => Execute(model, spc));
    }

    private static ElementModel? TryCreateModel(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetNode is not ClassDeclarationSyntax classDeclaration)
        {
            return null;
        }

        if (!classDeclaration.Modifiers.Any(static modifier =>
                modifier.IsKind(global::Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)))
        {
            return null;
        }

        if (context.TargetSymbol is not INamedTypeSymbol { TypeKind: TypeKind.Class } symbol)
        {
            return null;
        }

        if (!IsPrimaryAttributedDeclaration(context, symbol))
        {
            return null;
        }

        var fieldNames = symbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(static field => field.IsStatic && field.IsReadOnly &&
                                   SymbolEqualityComparer.Default.Equals(field.Type, field.ContainingType))
            .Select(static field => field.Name)
            .ToImmutableArray();

        if (fieldNames.IsDefaultOrEmpty)
        {
            return null;
        }

        return new ElementModel(
            symbol.ContainingNamespace.ToDisplayString(),
            symbol.Name,
            fieldNames);
    }

    private static bool IsPrimaryAttributedDeclaration(GeneratorAttributeSyntaxContext context, INamedTypeSymbol symbol)
    {
        var currentAttributeStart = context.Attributes
            .Select(static attribute => attribute.ApplicationSyntaxReference?.Span.Start ?? int.MaxValue)
            .DefaultIfEmpty(int.MaxValue)
            .Min();

        var firstAttributeStart = symbol.GetAttributes()
            .Where(static attribute => attribute.AttributeClass?.ToDisplayString() == AttributeMetadataName)
            .Select(static attribute => attribute.ApplicationSyntaxReference?.Span.Start ?? int.MaxValue)
            .DefaultIfEmpty(int.MaxValue)
            .Min();

        return currentAttributeStart == firstAttributeStart;
    }

    private static void Execute(ElementModel model, SourceProductionContext context)
    {
        var source = GeneratePartialClass(model.NamespaceName, model.ClassName, model.FieldNames);
        context.AddSource($"{model.ClassName}_Generated.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string GeneratePartialClass(string ns, string className, ImmutableArray<string> fields)
    {
        var sb = new StringBuilder();
        sb.Append($$"""
                    // <auto-generated/>
                    #nullable enable
                    using System;
                    using System.Collections.Generic;

                    namespace {{ns}};

                    public partial class {{className}}
                    {
                        private static readonly IReadOnlyList<{{className}}> _allElements = Array.AsReadOnly(new[]
                        {
                    
                    """);
        foreach (var field in fields)
        {
            sb.AppendLine($"        {field},");
        }

        sb.Append($$"""
                        });

                        private static readonly {{className}}?[] _elementsByValue = CreateElementsByValue();

                        private static {{className}}?[] CreateElementsByValue()
                        {
                            byte maxValue = 0;
                    """);

        foreach (var field in fields)
        {
            sb.AppendLine($"        if ((byte){field}.Value > maxValue) maxValue = (byte){field}.Value;");
        }

        sb.Append($$"""

                            var elements = new {{className}}?[maxValue + 1];
                    """);

        foreach (var field in fields)
        {
            sb.AppendLine($"        elements[(byte){field}.Value] = {field};");
        }

        sb.Append($$"""

                            return elements;
                        }

                        public static IEnumerable<{{className}}> GetAll() => _allElements;

                        public static {{className}} FromValue(byte value) 
                        {
                            if (value < _elementsByValue.Length && _elementsByValue[value] is { } element)
                            {
                                return element;
                            }

                            throw new KeyNotFoundException($"Value {value} not found in {{className}}");
                        }
                    }
                    """);
        return sb.ToString();
    }

    private readonly struct ElementModel(string namespaceName, string className, ImmutableArray<string> fieldNames)
    {
        public string NamespaceName { get; } = namespaceName;

        public string ClassName { get; } = className;

        public ImmutableArray<string> FieldNames { get; } = fieldNames;
    }
}
